/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    colors: {
			template: "#F9F8F3",
			transparent: "transparent",
			green: "#00693F",
      darkgreen: "#012e1c",
      yellow:"#FFDB00",
      black:"#000000",
      white:"#ffffff",
      beige:"#f6f4ed",
      blueAgencyBorder: "#228BE6",
      blueAgencyForeground: "#1971C2",
      badgeLightBlue: "#BDDCFA",
      badgeDarkBlue: "#0A519A",
      textNeutral: "#46474E",
      borderGray: "#B9BBC0",
      borderPurple: "#BE4BDB",
      iconPurple: "#9C36B5",
      buttonBackgroundGray: "#FAFAFA",
      buttonBorderGray: "#EFEFF1",
      tan:"#e4dfce",
      bgGray: "#EFEFF1",
      dividerGray:"#3B3B40",
      hoverLightBlue: "#BDDCFA",
			gray: {
				100: "#f7fafc",
				600: "#959595",
				800: "#D3D4D9",
			},
			offwhite: "#F2F0E4",
			halfwhite: "#F6F6F0",
			activegreen: "#3B7F73",
			icongray: "#F2F0E4",
		},
    fontSize: {
      sm: '0.8rem',
      base: '1rem',
      xl: '1.25rem',
      '2xl': '1.563rem',
      '3xl': '1.953rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
      '6xl': '4em',
    },
    extend: {},
  },
  content: [
    './assests/src/scripts/**/*.js',
    './views/**/*.php',
    './partials/**/*.php',
    './page-templates/**/*.php',
    './post-templates/**/*.php',
    './template-parts/**/*.php',
    './inc/**/*.php',
    './header.php',
    './woocommerce/*.php',
    './woocommerce/**/*.php',
    './404.php',
    './archive.php',
    './comments.php',
    './footer.php', 
    './header.php',
    './index.php',
    './page.php',
    './search.php',
    './searchform.php',
    './single.php',
  ],
}